### ISSUE TITLE
Including plugins

### ISSUE THREAD

**Issue by ajaypillay** [Apollinaire/meteor-mdx#1]
Hi, thank you for creating this package.

I need to use plugins as I need to display [Math blocks](https://mdxjs.com/guides/math-blocks). Going through the code, I saw that it was added as a todo in the comments.

I'm not sure if I can help actually be able to send in plugins but I was hoping to be able to hardcode it into my local copy of the package but I couldn't quite do so.

Do you have any advice on how I can modify this, short of pushing my own package with all of it hardcoded in?

Thanks!

**Comment by Apollinaire** [comment]
Hi, I would recommend to fork the repo and hardcode your plugins directly into the compiler.js file. I don't remember how you can work with a compiler package locally, but I'm not sure you'll have to push the package all the way to atmosphere.
Reading https://github.com/mdx-js/mdx/discussions/1570 it seems that you managed to do this by yourself? If you did I'd like to see the result.

Keep in mind that this package has been written 3 years ago as a side project, and that I don't use it anymore. So there might be some outdated or broken things.

**Comment by ajaypillay** [comment]
Hi @Apollinaire thanks for your response, and yes I actually managed to hardcode it in, though it took a LOT of troubleshooting (as is expected, but the troubleshooting was mainly due to updating the dependencies and things changing, coupled with the fact that I had never actually done this before).

> Keep in mind that this package has been written 3 years ago as a side project, and that I don't use it anymore. So there might be some outdated or broken things.

No worries, completely understandable.

I managed to figure out how to make the package for myself.

## Step 1: Creating your own local package

In order to create your own local package, it has to be in the `packages/` directory, [as per option 1 here in the Meteor docs](https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages).

## Step 2: How a local package gets identified

I didn't fork the repo but instead cloned it directly into this `packages/` directory (same thing really, I just didn't set up any repository for version control, but will do so eventually). I called this package `foo`. So, now the package lies in `packages/foo`. Now I had to run `meteor add foo`, or you can just add the package `foo` at the end of the file `.meteor/packages`. Because there is a `packages` directory, Meteor looks inside this first before searching Atmosphere during its build.

## Step 3: Modify `package.js`

[For reference: original file in this repo](https://github.com/Apollinaire/meteor-mdx/blob/master/package.js).

I had to change the name to `foo` and fix the dependencies:
```
 Package.describe({
   name: 'foo',
   version: '0.0.5',
   summary: 'Compiler plugin that supports MDX files in Meteor',
   git: 'https://github.com/Apollinaire/meteor-mdx',
   documentation: 'README.md',
 });

 Package.registerBuildPlugin({
   name: 'compile-mdx',
   use: [
     'ecmascript',
     'babel-runtime',
     'babel-compiler@7.6.1',
     'caching-compiler@1.2.1',
   ],
   sources: [
     'compiler.js',
     'plugin.js',
   ],
   npmDependencies: {
     '@mdx-js/mdx': '1.6.22',
     "rehype-katex": "4.0.0",
     "remark-gfm": "1.0.0",
     "remark-math": "3.0.1",
     '@babel/runtime': '7.14.0'
   },
 });
```
As noted in [mdx-js/mdx#1570](https://github.com/mdx-js/mdx/discussions/1570#discussion-3391959), `mdx@1.X.X` is compatible with `remark-math` with a version strictly less than 4, and `mdx@2.X.X` is compatible with `remark-math` with a version greater than or equal to 4. I wanted to use `remark-gfm` as well so I included that too. In the interim when I was testing I was getting some babel-runtime errors so I included the `babel-runtime` Meteor package and `@babel/runtime` NPM package to fix that. It might've been due to updated dependencies or something but I'm not really sure why it was needed, but it was breaking without it.

## Step 4: Modify `compiler.js`

[For reference: original file in this repo](https://github.com/Apollinaire/meteor-mdx/blob/master/compiler.js).

I had to include these two imports:
```
const remarkMath = require("remark-math")
const rehypeKatex = require("rehype-katex")
```
I will note that I had to strictly use this method of import instead of the traditional `import X from "package"`, that meant that `X` was undefined in the `compileOneFile` function. Not sure why this was the case.

In the `compileOneFile` function, I updated the `const jsx` declaration to this:
```
const jsx = mdx.sync(content, { remarkPlugins: [remarkMath], rehypePlugins: [rehypeKatex]});
```
`mdx.sync` can take in the plugins in its second argument. [It's not shown on the MDX sync API page](https://mdxjs.com/advanced/api) but is shown on the [how to use remark and rehype plugins page](https://mdxjs.com/advanced/plugins). I think that it should also be stated explicitly on the `sync` page that this can be done and linking to that page instead of having to hunt it down on another page.

The last thing is to update the `mdx` import for the `jsxComplete` string. This was the biggest pain because I couldn't figure out where `mdx` should be correctly imported from in the latest `mdx` version `1.6.22`. (the package originally had it at `0.16.6`!)
```
const jsxComplete = `
import React from 'react'
import { mdx } from '@mdx-js/react'
${jsx}
      `;
```

## Done
And then you should be golden. It still doesn't really address how you customize a selection of plugins to include, but I may revisit that at a later stage.

I will also note that I didn't actually include `remark-gfm` in the `remarkPlugins` array because I wanted to get the LaTeX working correctly first, but it **shouldn't** throw any errors by including it.

**Comment by Apollinaire** [comment]
Thanks for all these precise explainations. I don't remember how I developed this package locally, and I had doubts that putting it directly in `/packages` would work since this is a compiler package, and well, I guess it needs to be compiled to work. But it's great to know that it works, meteor shines again by its awesome build system.
To make it work without hardcoding the plugins would require creating a settings file, like `.mdxrc`, parse it, `require` the plugins and pass them to `mdx`. But I have no time and no reason to do this since I'm not using this. Accepting PRs though!
I'm glad the package could help you!

**Comment by ajaypillay** [comment]
Thanks for the explanation on how to get started with passing in options. I will look into submitting a PR for that at some point.
